### ISSUE TITLE
video is not updated if I join later

### ISSUE THREAD

**Issue by CrismaruIlie** [tusharmoraye/WatchYoutubeTogether#27]
Hello, there is a bug where video is not updated if I join later on.

**Comment by tusharmoraye** [comment]
Hi @EliasNetSeek 
I am not able to reproduce the issue.
Can you please explain in detail or provide steps to reproduce?

**Comment by CrismaruIlie** [comment]
HI, I've tried to reproduce the bug but without success. With 2 rooms opened, each one with different media playing, if you join on either one the same media will be played. Do you have plans to extend this project ?

**Comment by tusharmoraye** [comment]
I don't have any plan to extend this project as of now.
